[workspace]
resolver = "2"
members = ["core", "methods", "app"]
#exclude = ["lib"]


[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]

risc0-build = { version = "1.1.1", features = ["docker"] }
risc0-zkvm = { version = "1.1.1", default-features = false, features = ["client"] }
risc0-zkp = { version = "1.1.1", default-features = false }

risc0-build-ethereum = { git = "https://github.com/risc0/risc0-ethereum", tag = "v1.1.1" }
risc0-ethereum-contracts = { git = "https://github.com/risc0/risc0-ethereum", tag = "v1.1.1" }

methods = { path = "./methods" }
pkcs7-core = { path = "core" }

alloy-primitives = { version = "0.8.8", default-features = false, features = ["rlp", "serde", "std"] }
alloy-sol-types = { version = "0.8.8" }
anyhow = { version = "1.0.75" }
bincode = { version = "1.3" }
bytemuck = { version = "1.19" }
ethers = { version = "2.0" }
hex = { version = "0.4" }
log = { version = "0.4" }
serde = { version = "1.0", features = ["derive", "std"] }

#apps


[profile.release]
debug = 1
lto = true
